const ContactsData = [
  {
    id: 1,
    image: 'assets/images/users/avatar-3.jpg',
    name: 'Adam Miller',
    mobile: '+91 80558 44829',
    designation: 'Senior Manager',
    alternateMobile: '+91 80558 44829',
    email: 'Adam@primary.com',
    secondaryEmail: 'Adam@secondary.com',
    addressLine: '858, Caanl Carter Road',
    addressLine2: 'Near Galaxy Church',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    zipcode: '440013',
  },
  {
    id: 2,
    name: 'Andrue Michel',
    mobile: '9876543211',
    designation: 'Managing Director',
    alternateMobile: '+91 80558 44829',
    email: 'Andrue@primary.com',
    secondaryEmail: 'Andrue@secondary.com',
    addressLine: '858, Caanl Carter Road',
    addressLine2: 'Near Galaxy Church',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    zipcode: '440013',
  },
  {
    id: 3,
    name: 'Aomson Chark',
    mobile: '9876543211',
    designation: 'Project Manager',
    alternateMobile: '+91 80558 44829',
    email: 'Aomson@primary.com',
    secondaryEmail: 'Aomson@secondary.com',
    addressLine: '858, Caanl Carter Road',
    addressLine2: 'Near Galaxy Church',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    zipcode: '440013',
  },
  {
    id: 4,
    image: 'assets/images/users/avatar-2.jpg',
    name: 'Steven Franklin',
    mobile: '9876543211',
  },
  {
    id: 5,
    name: 'Keith Gonzales',
    mobile: '9876543211',
    designation: 'CEO',
    alternateMobile: '+91 80558 44829',
    email: 'Keith@primary.com',
    secondaryEmail: 'Keith@secondary.com',
    addressLine: '858, Caanl Carter Road',
    addressLine2: 'Near Galaxy Church',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    zipcode: '440013',
  },
  {
    id: 6,
    image: 'assets/images/users/avatar-4.jpg',
    name: 'Jose Vickery',
    mobile: '9876543211',
    designation: 'CEO',
    alternateMobile: '+91 80558 44829',
    email: 'Jose@primary.com',
    secondaryEmail: 'Jose@secondary.com',
    addressLine: '858, Caanl Carter Road',
    addressLine2: 'Near Galaxy Church',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    zipcode: '440013',
  },
  {
    id: 7,
    name: 'Mitchel Givens',
    mobile: '9876543211',
    designation: 'CEO',
    alternateMobile: '+91 80558 44829',
    email: 'Givens@primary.com',
    secondaryEmail: 'Givens@secondary.com',
    addressLine: '858, Caanl Carter Road',
    addressLine2: 'Near Galaxy Church',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    zipcode: '440013',
  },
];

export { ContactsData };
