const tableData = [
  {
    name: 'Timoteo Lyddy',
    position: 'Quality Engineer',
    company: 'Vidago',
    email: 'Timoteo@gmail.com',
    contact: '+919797979797',
    stage: 'Client',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/Vinit.jpg',
    },
  },
  {
    name: 'Cherye Bleby',
    position: 'Quality Engineer',
    company: 'La Concordia',
    email: 'Cherye@gmail.com',
    contact: '+919797979797',
    stage: 'Prospect',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/Shubham.jpg',
    },
  },
  {
    name: 'Timoteo Lyddy',
    position: 'Quality Engineer',
    company: 'Vidago',
    email: 'Timoteo@gmail.com',
    contact: '+919797979797',
    stage: 'Client',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/Vinit.jpg',
    },
  },
  {
    name: "Zacharias O'Shaughnessy",
    position: 'Senior Editor',
    company: 'Maungatapere',
    email: 'Zacharias@gmail.com',
    contact: '+919797979797',
    stage: 'Prospect',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/Shubham.jpg',
    },
  },
  {
    name: 'Timoteo Lyddy',
    position: 'Quality Engineer',
    company: 'Vidago',
    email: 'Timoteo@gmail.com',
    contact: '+919797979797',
    stage: 'Client',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/Vinit.jpg',
    },
  },
  {
    name: "Zacharias O'Shaughnessy",
    position: 'Senior Editor',
    company: 'Maungatapere',
    email: 'Zacharias@gmail.com',
    contact: '+919797979797',
    stage: 'Do Not Call',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/Shubham.jpg',
    },
  },
  {
    name: 'Timoteo Lyddy',
    position: 'Quality Engineer',
    company: 'Vidago',
    email: 'Timoteo@gmail.com',
    contact: '+919797979797',
    stage: 'Do Not Call',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/Vinit.jpg',
    },
  },
  {
    name: 'Cherye Bleby',
    position: 'Quality Engineer',
    company: 'La Concordia',
    email: 'Cherye@gmail.com',
    contact: '+919797979797',
    stage: 'Do Not Call',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/Shubham.jpg',
    },
  },
  {
    name: 'Timoteo Lyddy',
    position: 'Quality Engineer',
    company: 'Vidago',
    email: 'Timoteo@gmail.com',
    contact: '+919797979797',
    stage: 'Not Interested',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/Vinit.jpg',
    },
  },
  {
    name: 'Cherye Bleby',
    position: 'Quality Engineer',
    company: 'La Concordia',
    email: 'Cherye@gmail.com',
    contact: '+919797979797',
    stage: 'Not Interested',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/Shubham.jpg',
    },
  },
  {
    name: "Zacharias O'Shaughnessy",
    position: 'Senior Editor',
    company: 'Maungatapere',
    email: 'Zacharias@gmail.com',
    contact: '+919797979797',
    stage: 'Not Interested',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/Shubham.jpg',
    },
  },
  {
    name: 'Timoteo Lyddy',
    position: 'Quality Engineer',
    company: 'Vidago',
    email: 'Timoteo@gmail.com',
    contact: '+919797979797',
    stage: 'Connected',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/Vinit.jpg',
    },
  },
  {
    name: 'Cherye Bleby',
    position: 'Quality Engineer',
    company: 'La Concordia',
    email: 'Cherye@gmail.com',
    contact: '+919797979797',
    stage: 'Interested',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/Shubham.jpg',
    },
  },
  {
    name: "Zacharias O'Shaughnessy",
    position: 'Senior Editor',
    company: 'Maungatapere',
    email: 'Zacharias@gmail.com',
    contact: '+919797979797',
    stage: 'Connected',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/Shubham.jpg',
    },
  },
  {
    name: 'Odie Jentin',
    position: 'Programmer II',
    company: 'Grabovci',
    email: 'Odie@gmail.com',
    contact: '+919797979797',
    stage: 'Interested',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/abc.jpg',
    },
  },
  {
    name: 'Eugenie Sang',
    position: 'Operator',
    company: 'Oxbow',
    email: 'Eugenie@gmail.com',
    contact: '+919797979797',
    stage: 'Connected',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/abc.jpg',
    },
  },
  {
    name: 'Sammy Guyers',
    position: 'Mechanical Systems Engineer',
    company: 'Sanhe',
    email: 'Sammy@gmail.com',
    contact: '+919797979797',
    stage: 'In Progress',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Shubham Bodade',
      profilePic: 'path/Shubham.jpg',
    },
  },
  {
    name: 'Tarah Blick',
    position: 'Paralegal',
    company: 'Fylí',
    email: 'Tarah@gmail.com',
    contact: '+919797979797',
    stage: 'Interested',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/abc.jpg',
    },
  },
  {
    name: 'Jemie Ormshaw',
    position: 'Systems Administrator II',
    company: 'Vila Fria',
    email: 'Jemie@gmail.com',
    contact: '+919797979797',
    stage: 'In Progress',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/abc.jpg',
    },
  },
  {
    name: 'Gerrie Semeradova',
    position: 'Research Associate',
    company: 'Balykchy',
    email: 'Gerrie@gmail.com',
    contact: '+919797979797',
    stage: 'Interested',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Praveer D',
      profilePic: 'path/abc.jpg',
    },
  },
  {
    name: 'Ottilie Mostyn',
    position: 'Accounting Assistant II',
    company: 'Eskilstuna',
    email: 'Ottilie@gmail.com',
    contact: '+919797979797',
    stage: 'Connected',
    lastContacted: '05 Aug 2020',
    dateModified: '2018/12/04',
    salesOwner: {
      id: 1,
      name: 'Shubham Bodade',
      profilePic: 'path/Shubham.jpg',
    },
  },
];

export { tableData };
