const kanbanList = [
  {
    id: 1,
    client_name: 'John Stevens',
    date: '5 Aug, 2020',
    client_email: 'john.stevens.razorback',
    client_contact: '+91 8055855829',
    client_designation: 'Sales Manager',
    client_location: 'Razorback, India',
    user: ['assets/images/users/avatar-1.jpg'],
    managed_by: 'Praveer Darbeshwar',
    status: 'contacted',
  },
  {
    id: 2,
    client_name: 'John Stevens',
    date: '5 Aug, 2020',
    client_email: 'john.stevens.razorback',
    client_contact: '+91 8055855829',
    client_designation: 'Sales Manager',
    client_location: 'Razorback, India',
    user: ['assets/images/users/avatar-1.jpg'],
    managed_by: 'Shubham Bodade',
    status: 'contacted',
  },
  {
    id: 3,
    client_name: 'John Stevens',
    date: '6 Aug, 2020',
    client_email: 'john.stevens.razorback',
    client_contact: '+91 8055855829',
    client_designation: 'Sales Manager',
    client_location: 'Razorback, India',
    user: ['assets/images/users/avatar-1.jpg'],
    managed_by: 'Kunal Joshi',
    status: 'contacted',
  },
  {
    id: 4,
    client_name: 'John Stevens',
    date: '10 Aug, 2020',
    client_email: 'john.stevens.razorback',
    client_contact: '+91 8055855829',
    client_designation: 'Sales Manager',
    client_location: 'Razorback, India',
    user: ['assets/images/users/avatar-1.jpg'],
    managed_by: 'Shrunkhla Sonone',
    status: 'interested',
  },
  {
    id: 5,
    client_name: 'John Stevens',
    date: '13 Aug, 2020',
    client_email: 'john.stevens.razorback',
    client_contact: '+91 8055855829',
    client_designation: 'Sales Manager',
    client_location: 'Razorback, India',
    user: ['assets/images/users/avatar-1.jpg'],
    managed_by: 'Sameera Kelkar',
    status: 'interested',
  },
  {
    id: 6,
    client_name: 'John Stevens',
    date: '13 Aug, 2020',
    client_email: 'john.stevens.razorback',
    client_contact: '+91 8055855829',
    client_designation: 'Sales Manager',
    client_location: 'Razorback, India',
    user: ['assets/images/users/avatar-1.jpg'],
    managed_by: 'Praveer Darbeshwar',
    status: 'interested',
  },
  {
    id: 7,
    client_name: 'John Stevens',
    date: '10 Aug, 2020',
    client_email: 'john.stevens.razorback',
    client_contact: '+91 8055855829',
    client_designation: 'Sales Manager',
    client_location: 'Razorback, India',
    user: ['assets/images/users/avatar-1.jpg'],
    groupId: 3,
    managed_by: 'Praveer Darbeshwar',
    status: 'inprogress',
  },
  {
    id: 8,
    client_name: 'John Stevens',
    date: '09 Aug, 2020',
    client_email: 'john.stevens.razorback',
    client_contact: '+91 8055855829',
    client_designation: 'Sales Manager',
    client_location: 'Razorback, India',
    user: ['assets/images/users/avatar-1.jpg'],
    groupId: 3,
    managed_by: 'Praveer Darbeshwar',
    status: 'inprogress',
  },
  {
    id: 9,
    client_name: 'John Stevens',
    date: '15 Aug, 2020',
    client_email: 'john.stevens.razorback',
    client_contact: '+91 8055855829',
    client_designation: 'Sales Manager',
    client_location: 'Razorback, India',
    user: ['assets/images/users/avatar-1.jpg'],
    groupId: 3,
    managed_by: 'Praveer Darbeshwar',
    status: 'inprogress',
  },
];

export { kanbanList };
